services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000' # MinIO API
      - '9001:9001' # MinIO Web UI
    volumes:
      - ./minio_data:/var/lib/minio/data
    env_file:
      - .env
    command: server --console-address ":9001" /var/lib/minio/data
